### ISSUE TITLE
Different edge drawing algorithm for different edge directions

### ISSUE THREAD

**Issue by bergie** [flowhub/the-graph#1]
Instead of having a single edge drawing algorithm, we should look at the heading of the edge (from source node to target node), and pick the right algorithm:
- E, NE, SE: from right side to left side, possibly with a curve
- S: from bottom to top, possibly with a curve
- N, NW, W: from bottom to left with a curve passing both nodes
- SW: from bottom to top, with a curve passing both nodes

**Comment by xtrasmal** [comment]
Are you guys working on the  45° algo still? All that rounded stuff might work nice, but I'd like to see piping like in circuit board designs. 

Check out the video at about 1:34 min
http://www.altium.com/altium-designer/overview

That looks pretty good.

**Comment by xtrasmal** [comment]
And the video's here might inspire some new ideas too: http://www.altium.com/altium-designer/features?field_ad_version_tid=All&tid=stress-free

**Comment by xtrasmal** [comment]
The idea of having multilayers of lines is pretty sweet.

**Comment by forresto** [comment]
Circuit board constraints (short circuits) and different than ours (following paths on screen). Both could be improved with smarter routing, but I'm sticking with curves.

**Comment by xtrasmal** [comment]
Curves are clunky, spaggetti.That and the rounded edges in the new design makes the whole experience feel bleh
