### ISSUE TITLE
Pinch-to-zoom loses zoom level

### ISSUE THREAD

**Issue by bergie** [flowhub/the-graph#108]
Pinch-to-zoom seems to always start from the zoom/pan level that you had on the first time you pinched.

Instead, it should start from where you're when you start the gesture

![screencast 1](https://f.cloud.github.com/assets/3346/2334803/04e9c64e-a47d-11e3-92c2-b7cdc8e8ee03.gif)

**Comment by jonnor** [comment]
Should work fine now. Not seen this in a couple of years...
