### ISSUE TITLE
Work around Polymer ShadowDOM bug on PhoneGap

### ISSUE THREAD

**Issue by bergie** [flowhub/the-graph#124]
Currently Polymer ShadowDOM/PointerEvents bug Polymer/ShadowDOM#394 is killing noflo-ui on mobile when built with PhoneGap. `the-graph` crashes and disappears on first touch gesture.

We need to implement a workaround ASAP. Some suggestions in Polymer/PointerEvents#131

**Comment by jonnor** [comment]
Not doing PhoneGap builds anymore, closing.
