### ISSUE TITLE
Pie menu styling

### ISSUE THREAD

**Issue by bergie** [flowhub/the-graph#136]
Here is the [original design](http://dribbble.com/shots/1334136-flowhub?list=users&offset=3):

![screenshot 2014-04-07 at 15 11 34](https://cloud.githubusercontent.com/assets/3346/2631234/33ceeb4a-be56-11e3-9689-d32047733785.png)

It is quite important to strongly show the option user is about to select

**Comment by jonnor** [comment]
Current state seems to work OK
