### ISSUE TITLE
PointerEvents and PointerGestures deprecated

### ISSUE THREAD

**Issue by forresto** [flowhub/the-graph#145]
Move to: https://github.com/Polymer/polymer-gestures

Info: https://groups.google.com/d/msg/polymer-dev/ba4aDyOozm8/Hw0GJLvcOCMJ

todo
- ~~event.clientX to event.x~~
- ~~edge preview pointermove to track~~
- pinch https://github.com/Polymer/polymer-gestures/issues/3

**Comment by jonnor** [comment]
Is this issue still valid?

**Comment by jonnor** [comment]
Seems we're using `PolymerGestures` now.
