### ISSUE TITLE
Create factory functions to allow for element modification.

### ISSUE THREAD

**Issue by hayesmg** [flowhub/the-graph#151]
I'd like to propose that elements that are displayed in the editor be created using factory functions.

I am currently attempting to adjust the way a node is presented on screen.  My requirement is that I be able to adjust size and position attributes of a node's background, border, labels, icon, and sublabels.

In the current `the-graph-node.js` file, the React elements are created directly:

``` js
React.DOM.rect({
  className: "node-bg", // HACK to make the whole g draggable
  width: TheGraph.nodeSize,
  height: TheGraph.nodeSize + 35
}),
React.DOM.rect({
  className: "node-border drag",
  width: TheGraph.nodeSize,
  height: TheGraph.nodeSize,
  rx: TheGraph.nodeRadius,
  ry: TheGraph.nodeRadius
}),
```

My proposal is that many (all?) React.DOM calls be abstracted away to allow for interception:

Proposed code attached to root `TheGraph` object:

``` js
TheGraph.createNode = function(options) {
    return React.DOM.g(
        TheGraph.createNodeBackground({ className: 'node-bg' }),
        TheGraph.createNodeBorder({ className: 'node-border drag' }),
        // etc...
    );
}
TheGraph.createNodeBackground = function(options) {

    // Here could be some code for defaults, such as:
    if (!options.width)
        options.width = TheGraph.nodeSize;

    return React.DOM.rect(options);
}

TheGraph.createNodeBorder = function(options) {
    return React.DOM.rect(options);
}
```

Then the file `the-graph-node.js` would have a simple call in it's render function:

``` js
render: function() {
    // other code...
    return TheGraph.createNode(options);
}
```
### Usage

With that in place, I could intercept each call and adjust all attributes accordingly:

``` js
var baseCreateNodeBackground = TheGraph.createNodeBackground;
TheGraph.createNodeBackground = function(options) {
    options.width = 200; // Increase width
    options.height = 50; // Decrease height
    return baseCreateNodeBackground(options);
}
```

**Comment by jonnor** [comment]
Looks to be fixed in PR #157
