### ISSUE TITLE
the-graph-editor must be positioned at 0,0

### ISSUE THREAD

**Issue by octavioturra** [flowhub/the-graph#160]
When I've tried to interop the-graph-editor with another polymer elements like scaffold, edges started to have strange offset behavior. This was the same for labels.

![strange_behavior](https://cloud.githubusercontent.com/assets/838778/4080438/938667ea-2ede-11e4-8a0a-f3d7ef3e2e2e.png)

I've got the same problem using position asolute container as wrapper to the editor.

![strange_behavior_2](https://cloud.githubusercontent.com/assets/838778/4080478/03981948-2edf-11e4-86b5-8b8656bddb5a.png)

Is this an intentional behavior or a bug?

**Comment by epatters** [comment]
Thanks for this project; it looks very nice. Was this issue ever resolved? It is now possible to embed the-graph into a web page without occupying the full page?

**Comment by YanDoroshenko** [comment]
@epatters Take a look at https://github.com/kbss-cvut/s-pipes-editor

**Comment by epatters** [comment]
Thanks @YanDoroshenko. From looking at [ViewController.js](https://github.com/kbss-cvut/s-pipes-editor/blob/master/src/main/webapp/js/components/view/ViewController.js), I gather that you were able to successfully embed the-graph into a reusable React component? If so, that is excellent for my purposes.

**Comment by YanDoroshenko** [comment]
@epatters Yep. I had to use `require` instead of `import` because that's the only way it worked and I'm not a JS guy, but yes, it kinda worked.
