### ISSUE TITLE
Cleaner handling for missing component info

### ISSUE THREAD

**Issue by bergie** [flowhub/the-graph#174]
I'm seeing this occasionally:

![screenshot 2014-09-16 at 13 06 38](https://cloud.githubusercontent.com/assets/3346/4286232/9b311bfe-3d91-11e4-9d19-78f6bf65a1f1.png)

**Comment by jonnor** [comment]
Now you get warnings in console. In future will throw, since this is a bug on callers part, not providing correct component `library`
