### ISSUE TITLE
Semantics or heuristics for edges' colors

### ISSUE THREAD

**Issue by automata** [flowhub/the-graph#185]
Any thoughts about automatic color attribution to edges?
- Edges going from the same component to other components have the same color: easier to find the source of those edges.
- Edges with the same datatype have the same color (and same inport/outport "connector" color?): easier to follow the flow by datatype

What heuristics do you use when colorizing edges?

**Comment by bergie** [comment]
@automata at one point of noflo-ui development we had default colors for wires come from the data types, but in practice I usually want to give them application-specific semantic coloring.

One exception that could be useful would be to default wires coming from `error` ports to red.

**Comment by jonnor** [comment]
Any such semantics should be in the application using the-graph, not in the library itself. If someone wants to implement this and not enough API is supported for overriding edge colors etc, please file a bug about that.
