### ISSUE TITLE
fluxify with noflo

### ISSUE THREAD

**Issue by forresto** [flowhub/the-graph#186]
Attempting some top-down design:

![screen shot 2014-11-06 at 12 19 29 pm](https://cloud.githubusercontent.com/assets/395307/4940292/20c22046-65d9-11e4-9955-75d3dc204c23.png)

```
NoFloIn(noflo-graph-inport) GRAPH -> GRAPH MakeGraphActions(listen-noflo-and-update) ACTION -> ACTION Dispatch(throttle-and-batch-rAF) 
Dispatch() NEW_GRAPH -> GRAPH MakeLibraryStore(component-library) LIBRARY -> LIBRARY MakeGraphStore(whole-view-state)
Dispatch() NEW_GRAPH -> GRAPH MakeGraphStore(whole-view-state) STATE -> STATE Render(UpdateReact)
MakeLibraryStore() LIBRARY -> LIBRARY MakeGraphStore()
RuntimeIns(component-def-icon-etc) IN -> IN MakeRuntimeActions(to-actions) ACTION -> ACTION Dispatch() LIB_ACTION -> ACTION MakeLibraryStore()
Dispatch() GRAPH_ACTION -> ACTION MakeGraphStore()
Render(UpdateReact) EVENT -> EVENT MakeGraphActions()
```

Questions:
1. `MakeGraphActions` will be a listener for noflo.Graph `endTransaction`. It will listen for graph editing events from the view to apply to the noflo.Graph (which will in turn fire `endTransaction`). Is that a reasonable connection?
2. `MakeGraphActions` will also process non-noflo-chaging events, like zoom/pan/select. Should those be a separate action creator? That would require two loopbacks from the view, or one and a new component to route them.
3. Should we worry about dealing with a new graph here, or just make a new editor above here? 
4. If we deal with new graphs, should the library reset at that point? We would need to get the info from the runtime again. (I think the current icon bug has something to do with this.)
5. Is `Dispatch` the right place to throttle updates via `requestAnimationFrame`? There could also be an option to wait for a `tick` from noflo-ui's main rAF loop.
6. Where should graph outports (selection changed etc.) be wired? Maybe to `Dispatch`, after the actions have been sent to the stores?

**Comment by yousefmoazzam** [comment]
Hi all, I'm working on a project that is in a somewhat similar vain to points brought up in this discussion; I'm attempting to integrate the-graph into a Flux app and am currently working on removing Polymer (and also have a goal of hopefully removing the NoFlo dependency at a later stage). 

What I've tried so far in my endeavour to remove Polymer is simply to move everything from custom Polymer elements to javascript objects and have had some decent results, I've managed to remove the polymer.js and webcomponents.js imports and still display the-graph, albeit with a few caveats (the biggest one being no gestures as I have removed PolymerGestures but not yet replaced it).

I'm specifically curious about the talk of implementing a Flux pattern and the idea of getting the logic out of Polymer elements: I was wondering if a similar sort of idea of putting the-graph into a Flux architecture is currently being worked on, and also if removing Polymer is currently being worked on?

**Comment by jonnor** [comment]
Hi @yousefmoazzam, things are quite quiet, see #222 for Polymer related status.
Will you share your progress somewhere?

There was previously an idea about splitting out NoFlo.graph from rest of NoFlo, as it can be useful independently (mentioned in microflo/microflo#42). This should be the only thing the-graph depends on in NoFlo.

**Comment by yousefmoazzam** [comment]
Hi @jonnor , thanks for the quick reply! Ah ok, I saw that open issue before, I'll make sure to keep an eye on that then. 

Of course, here's the link to the repo I'm working on: https://github.com/yousefmoazzam/the-graph. The '2dirpcomp-edited.html' file in the 'the-graph-editor' folder is the one to run to see how well/not well what I've done works, and the 'theGraphHTMLRewrittenInJS.js' and 'theGraphEditorHTMLRewrittenInJS.js' files in the 'the-graph-edited' folder are the files showing the majority of what I've done.

And thank you for pointing me to that issue regarding NoFlo, I hadn't come across that one; removing NoFlo completely would be the ideal situation for the project, but whittling the dependency down to a decent minimum is definitely useful.

**Comment by jonnor** [comment]
There is no NoFlo dependency in this project anymore, and I don't plan to add it again.
