### ISSUE TITLE
buildInitialLibrary breaks new graphs

### ISSUE THREAD

**Issue by davidmaxwaterman** [flowhub/the-graph#210]
https://github.com/the-grid/the-graph/blob/master/the-graph-editor/the-graph-editor.html#L275

Could someone uncomment the code that is currently commented out? My current workaround is to basically assign an empty function to buildInitialLibrary, then assign to graph (invoking graphChanged()), and then to assign it back again in an async()....something I consider a horrible hack.

**Comment by jonnor** [comment]
`buildInitialLibrary` is now gone! Library must be explicitly passed from outside by consumers
