### ISSUE TITLE
how to reset graph to initial state?

### ISSUE THREAD

**Issue by davidmaxwaterman** [flowhub/the-graph#213]
(forgive my psuedocode)
Is there a way to set a the-graph instance back to the initial state?

We have this structure :

```
<our-editor>
  <the-editor>
    graph
    nofloGraph
    <the-graph graph={{nofloGraph}}>
```

We have a button that is supposed to reset our editor back to its initial state, and we do that by :

```
<our-editor>.reset()
  <the-editor>.graph = {};
```

However, when reset() as above, and then load another graph, it is clear that there is still some 'state' left over from the previous graph - if a node in the new graph has the same key name as one in the old graph, then the new one inherits the ports from the old one. This is only obvious momentarily, so, for example, if the old node has an input port, and the new one has an output port, then the user can see that the 'new' node is added with an input port, but that then is removed and replaced with an output port.

The end result is correct, but we'd like to be sure that the 'reset()' is actually thorough. Is there any way to avoid this glitch?

**Comment by forresto** [comment]
State is a bit of a mess here, for which I take responsibility :bow: 

Would scrapping the whole `<the-graph>` element and mounting a new one be an acceptable workaround for now?

**Comment by davidmaxwaterman** [comment]
I'm not sure of your terminology - what is 'scrapping' and 'mounting'? The latter sounds like a React thing - I've really not delved much into React. Do you mean something React-ish?

My first thought about your suggestion was it was referring to the element itself, much like any other element, it can be deleted and recreated in javascript. I guess it is possible, but we have it inside another polymer element that is referenced in many places as this.$.graph, and recreating instances by javascript would mean we have to wrap that element in a containver div and use this.$.container.querySelector('the-graph') everywhere. A bit ugly, but we could give it a try.

Let me know if I've misunderstood your advice.

**Comment by davidmaxwaterman** [comment]
We don't have a ```<the-graph>``` element in our code - we use a ```<the-graph-editor>``` element.
It seems to be that it is infeasible to reach down into ```<the-graph-editor>``` and remove its ```<the-graph>``` element. ```<the-graph-editor>``` has many references to ```this.$.graph``` and I'd not only have to re-wire those (perhaps through a getter ```get graph() { this.shadowRoot.querySelector('#graph'); }```), but also attempt to do a boat load of setup for the new element, and who knows what other components get hooks from that first instance of ```<the-graph>```.

Any thoughts?

**Comment by forresto** [comment]
What about making a new instance of `the-graph-editor`? Pseudo:

```
<your-editor>.reset: function(){
  this.removeChild( this.editor )
  this.editor = new <the-graph-editor>
  this.appendChild( this.editor )
}
```

**Comment by davidmaxwaterman** [comment]
No, the editor is all wired into the rest of the app with signals and what-not (methods that set and get various structures deep within). I actually spent most of the day trying to make this work, but there is far too much that is done at startup that would need to be re-done if I were to remove the editor (and therefore the graph).
