### ISSUE TITLE
Get rid of Polymer

### ISSUE THREAD

**Issue by davidmaxwaterman** [flowhub/the-graph#222]
Hi,

I wonder if anyone can give me some information regarding no-flo's plans for moving to Polymer 1.0 from 0.5.X?

Thanks,

Max.

**Comment by Tranquillius** [comment]
Watch to ticket #215

**Comment by forresto** [comment]
If somebody proves that it can be done with noflo-ui without too much refactoring, and some benefit, then I can do the-graph. Otherwise, higher priority is to get rid of Polymer.

**Comment by davidmaxwaterman** [comment]
#215 is closed - is there any point in watching it?

I'm curious. What is the rationale for 'getting rid of polymer'?

**Comment by forresto** [comment]
In the-graph, it's an artifact... Should be a stand-alone React component.

In noflo-ui, I think a need to refactoring for clarity and speed.

**Comment by davidmaxwaterman** [comment]
OK, though I should say I've struggled more with React than with Polymer...web components are easy enough to re-use, but React components seem quite convoluted.
There are other polymer elements and I guess they may also be removed? I suppose this would help us move our work from Polymer 0.5 to 1.0 since the fact that these two versions can't be mixed means we're stuck on 0.5 (I'm told the intention is that the same won't be true of later versions and it's only an artefact of using beta software); also we've used /deep/ to modify the-graph/etc quite a lot and there is talk of that (and ::shadow) being removed from chrome, which will force our hand somewhat.
Anyway, please keep us all in the loop. Thanks!

**Comment by davidmaxwaterman** [comment]
FWIW, I'm lead to believe that switching from 0.5 to 1.0 is fairly straight forward, as these things go; but there's no mixing the two, so all such elements have to be done at the same time. I think that's correct....

**Comment by forresto** [comment]
Again, if it is an easy win for noflo-ui, we'll tackle it before bigger refactoring. I'll give it a shot this afternoon.

**Comment by davidmaxwaterman** [comment]
Did you have a go? Many big problems?

**Comment by forresto** [comment]
Yes, it's a bigger refactoring with how we are using attributes, but the wheels are in motion now.

**Comment by forresto** [comment]
... wheels were in motion, but stalled. Pushed some initial stuff to https://github.com/the-grid/the-graph/tree/polymer1 , if somebody else wants to take this on. Likely we'll have to maintain 2 branches, as noflo-ui will be a bigger refactoring.

**Comment by sepidam** [comment]
Hi,
I wonder if anyone could do new update regarding no-flo's plans for moving to Polymer 1.0 from 0.5.X  than last version in branch Polymer1?

thanks.

**Comment by freder** [comment]
why not focus on getting rid of the polymer dependency entirely? — why did you need it in the first place?

**Comment by sepidam** [comment]
I need it in terms of other components of my application, that all of them are developed with Polymer 1.0. so I have to convert  "the-graph" to Polymer 1.0

**Comment by freder** [comment]
sorry, my question was directed at the maintainers of `the-graph`.

**Comment by freder** [comment]
a while ago i was looking into the-graph, because i needed a graph editor for a project. i was wondering what polymer offers that you wouldn't be able to do with react.  — the only thing i found was (as far as i remember), that it implements custom mouse / pointer events like [`track`](https://github.com/the-grid/the-graph/search?utf8=%E2%9C%93&q=track&type=Code). but then again, i don't know much about polymer, so i'm sure there are other reasons.

**Comment by davidmaxwaterman** [comment]
From my perspective, and I'm somewhat clueless wrt to React, but using Polymer enables it to at least pretend to allow us to use the-graph without having to deal with React overly. I'm not sure if using React's versions of web components would mean having to commit to using React for the enclosing application too, including having to learn it/etc/etc. For sure, I managed to largely avoid having to learn React in order to use the-graph (-editor), but I did have to dig into it a little, and I was privileged to have a co-worked who did that when necessary so I didn't need to.
What do you think?

**Comment by forresto** [comment]
Polymer offers convenience of throwing in polymer.js library and <the-graph-editor> tag, and being able to interact with vanilla js idioms. React requires lower-level management of dataflow, and the pros and cons with that.

We're using Polymer a lot more in noflo-ui, so the-graph is stuck with the old version until we have time to refactor noflo-ui. That's not on our immediate roadmap.

In `the-graph` Polymer is mostly a wrapper, so you should be able to use the React components directly if desired.

**Comment by hgenru** [comment]
Also Polymer 0.5 use deprecated `::shadow` and `/deep/` this can cause problems in future.

**Comment by jonnor** [comment]
As mentioned in noflo/noflo-ui#537 proposed way forward is to

* Make the-graph be React-only, moving the Polymer components/wrappers into noflo-ui
