### ISSUE TITLE
How to use as dependency not documented

### ISSUE THREAD

**Issue by jonnor** [flowhub/the-graph#225]
The README only says how to install and run the-graph itself (useful when developing),
but not how to use it in another project. Expected is some 'install via bower/componentio' or something to that effect...

There are also some example code in the repo (the-graph-editor/...html ), but these are also not mentioned in the docs. (having them in an examples/ subdir would also made it easier to find)

**Comment by Daandelange** [comment]
@jonnor : Saying «the docs», do you mean the `readme.md` or is there a documentation somewhere ?

**Comment by jonnor** [comment]
There are no docs except for the Readme, or the code examples mentioned.

**Comment by Daandelange** [comment]
Ok, thanks. Just wondering.
I'm digging in this issue, I found no bower solution but with npm you can do the regular `npm install the-graph --save` to install it as an npm dependency. Gonna figure out how to use it now :)
