### ISSUE TITLE
Allow to render to SVG/image

### ISSUE THREAD

**Issue by jonnor** [flowhub/the-graph#287]
For getting a snapshot of a graph, and maybe sharing it outside the app that uses the-graph.
Could be used as basis for simple [visual diffing tools for FBP graphs](https://github.com/flowbased/fbp-diff/issues/2).

**Comment by jonnor** [comment]
I had hoped we could just use DOM-level rendering for this. I did a test with `dom-to-image` which was not successful, fails with some unspecified image error event when used on `the-graph-editor`. However, it worked fine for some `<textarea>` elements etc. https://github.com/flowbased/flowtrace/commits/visualdiff

Still to be tested are some of the SVG-aware DOM node rendering methods.

**Comment by forresto** [comment]
To start, do we want to viz JSON or FBP diffs? Both? If FBP I guess we need the autolayout step.

Have you tried to mount the-graph in Phantom to get a PNG?

Github doesn't support SVG upload, so even if we can output the SVG string diffbot will need to convert it.

**Comment by jonnor** [comment]
Not merged yet
