### ISSUE TITLE
Undefined FakeMouse mixin

### ISSUE THREAD

**Issue by betalb** [flowhub/the-graph#306]
Not sure where this mixin can be found, it is not defined in the-graph.js: [TheGraph.mixins.FakeMouse](https://github.com/the-grid/the-graph/blob/c3b6a15eb41d079c625e07359d212c9ebb84f0f4/the-graph/the-graph-graph.js#L85)

React 15 is throwing a warning in case of `undefined` mixin

```
ReactClass: You're attempting to include a mixin that is either null or not an object.
Check the mixins included by the component, as well as any mixins they include themselves.
Expected object but got undefined.
```

**Comment by jonnor** [comment]
@betalb Thanks for reporting, fixed now in git master. Have you found any other issues with React 15?
