### ISSUE TITLE
What is the minimum Internet Explorer version supported?

### ISSUE THREAD

**Issue by ryanzec** [flowhub/the-graph#311]
Just out of curiosity to know if this is something that we should even investigate for usage at my workplace, what it the minimum IE version this library is going to support?

**Comment by forresto** [comment]
You can test it here: http://flowhub.github.io/the-graph/the-graph-editor/index.html

**Comment by jonnor** [comment]
Unlikely to officially support IE versions prior to 10 by Flowhub team. As long as fixes needed are clean, contributions for IE8/9 welcomed though.

**Comment by jonnor** [comment]
Edge/IE11+
