### ISSUE TITLE
Update to React 15

### ISSUE THREAD

**Issue by jonnor** [flowhub/the-graph#317]
Currently using `0.14.3`

**Comment by jonnor** [comment]
Somewhat releated, `React.createFactory` is considered legacy. Instead one should use `React.createElement` at the callsite. This is for JSX compatibility. 

https://facebook.github.io/react/warnings/legacy-factories.html
https://facebook.github.io/react/blog/2014/10/14/introducing-react-elements.html#creating-a-reactelement
https://facebook.github.io/react/docs/react-without-jsx.html

Note that the-graph code will likely continue to be JSX free, but being compatible so others can use it is very good.

**Comment by bergie** [comment]
Related PRs:

* #323
* #324

**Comment by jonnor** [comment]
Fixed in #372
