### ISSUE TITLE
Upgrade to Polymer 2

### ISSUE THREAD

**Issue by kristianmandrup** [flowhub/the-graph#344]
I have a branch where I've successfully upgraded to Polymer 2 :)

[the-graph#polymer2](https://github.com/kristianmandrup/the-graph/tree/polymer2)

Would anyone be interested in helping out to clean it up further and also migrate to class based latest version of React? 

Cheers!

**Comment by kristianmandrup** [comment]
I have the basic class infrastructure in place [React and ES6](http://egorsmirnov.me/2015/09/30/react-and-es6-part4.html)

To make it work we need to upgrade the build pipeline from using Grunt and browserify to instead using latest Babel with Webpack 2 :) 

Please help out!

**Comment by jonnor** [comment]
Hi @kristianmandrup . When trying to create a PR for your 'polymer2' branch to look at the diff, I get "flowhub:master and kristianmandrup:polymer2 are entirely different commit histories."?

**Comment by jonnor** [comment]
We were planning to get rid of Polymer completely, https://github.com/flowhub/the-graph/issues/222#issuecomment-248283645

A challenge is that noflo-ui, which is our main user of the-graph, is Polymer pre-1.0 based. And we don't want to have to rewrite all the code in one go.
