### ISSUE TITLE
Read-only mode

### ISSUE THREAD

**Issue by bergie** [flowhub/the-graph#349]
It would be nice to be able to use the-graph also for displaying graphs in read-only mode. This means that things like zooming and context menu (for navigating deeper) should still be available, but no editing actions should be possible:

* Remove any context menu actions that modify the graph
* Disable dragging from a port to create edge
* Disable any keyboard shortcuts that modify the graph

etc.

**Comment by bergie** [comment]
We can use this in places like https://noflojs.org/visualize, as well as in Flowhub live mode once noflo/noflo-ui#695 lands

**Comment by jonnor** [comment]
Also want for menu callbacks to return a value signaling "don't show a menu".
