### ISSUE TITLE
Support for mobile devices?

### ISSUE THREAD

**Issue by MagicalTux** [flowhub/the-graph#355]
The README.md file seems to suggest "touchscreen friendliness" and the flowhub homepage mentions usage of tablet, however accessing app.flowhub.io (for example) shows "Preparing Flowhub" blinking, and nothing more (tested on iPhone with Chrome and iPad with Safari).

Is that it takes very very long to prepare, or are iPads not supported, or did I miss something?

**Comment by bergie** [comment]
Yes, right now iPads are not working due to the old Polymer version we're still using. On Android devices it works fine.

Tracking this in noflo/noflo-ui#694 

#356 should remove the last of Polymer dependencies from the-graph, after which this library should work fine with iOS.
