### ISSUE TITLE
Touch-only input broken

### ISSUE THREAD

**Issue by bergie** [flowhub/the-graph#364]
Here we refer to a `TouchInput` var, but that is not defined anywhere:

https://github.com/flowhub/the-graph/blob/master/the-graph/hammer.js#L85

**Comment by jonnor** [comment]
@bergie missing `Hammer.` I think. Which browsers/device does this happen on?

**Comment by bergie** [comment]
@jonnor Mobile Safari on iOS 11

**Comment by jonnor** [comment]
Was fixed in #365
