### ISSUE TITLE
Missing dist/ in NPM package

### ISSUE THREAD

**Issue by YanDoroshenko** [flowhub/the-graph#367]
How is one supposed to get the `dist/the-graph.js` bundle if `the-graph` library is an NPM dependency (specified in `package.json`)? After `npm install` I have all the sources in `node_modules/the-graph`, but no `dist` directory. Thanks.

**Comment by bergie** [comment]
In noflo-ui we're building the-graph in the same WebPack bundle as our other modules. But indeed, maybe it would make sense to include a pre-built version in the NPM module for those that don't want to build

**Comment by YanDoroshenko** [comment]
I don't use WebPack in my project so that's pretty much not an option for me. Please comment here after you've decided whether to include a pre-built library in the NPM module or not so that I can close the issue. Thanks.

**Comment by jonnor** [comment]
Just-released 0.10.3 contains the `dist/` directory, as will future releases. Thanks for reporting
