### ISSUE TITLE
Publish version with latest changes

### ISSUE THREAD

**Issue by danielcondemarin** [flowhub/the-graph#384]
Hi are there any plans to release a new version of the library?

**Comment by davecarlson** [comment]
I too would like to know this!

**Comment by jonnor** [comment]
I had hoped to fix the tests on Travis CI. I tried to debug it a bit, but ran out of time. I guess we'll just have to skip them for now.

**Comment by davecarlson** [comment]
I believe the render tests also break on local machines - it seems to be
related to the version of. NOde being used

**Comment by jonnor** [comment]
@davecarlson do you have an example `nodejs` version that reproduces the breaking tests?

**Comment by jonnor** [comment]
Made a new issue for breaking tests, https://github.com/flowhub/the-graph/issues/385

**Comment by davecarlson** [comment]
Give me 5 mins and i'll re-test

**Comment by jonnor** [comment]
`0.12.2` is now on NPM.
