### ISSUE TITLE
Background heat map

### ISSUE THREAD

**Issue by bergie** [flowhub/the-graph#49]
Currently the graph background is a passive dot grid. In the sketches however it had some additional features:
1. Red guide line every third grid unit
2. "Heatmap" showing the impact of currently selected node(s)

![screenshot 2013-11-18 at 18 29 15](https://f.cloud.github.com/assets/3346/1565015/0e6cee70-5078-11e3-98e1-764ff49e022f.png)

The heatmap should react to selection/highlighting state of nodes and show a brighter background for the grid under selected nodes, fading towards the regular dark background along the connections of that node

**Comment by jonnor** [comment]
Proposing to kill this, dubious benefit. CC @bergie
