### ISSUE TITLE
2d canvas / webgl

### ISSUE THREAD

**Issue by forresto** [flowhub/the-graph#67]
Thinking about React.js treating the browser [more like GPU / game engine programming](http://swannodette.github.io/2013/12/17/the-future-of-javascript-mvcs/) ("repaint whole app, only changed parts get wet"). 

The SVG #66 branch is going to make our current design nicer to implement. 

But planning for the future, I think we're going to end up doing everything in WebGL for the control and speed. How could [React's concept of virtual DOM](http://facebook.github.io/react/docs/reconciliation.html) be structured with FBP logic and WebGL views?

Cons:
- lack of css (?)

**Comment by jefffriesen** [comment]
These look interesting:
https://github.com/Izzimach/react-three
https://github.com/Izzimach/react-pixi

**Comment by jonnor** [comment]
Not gonna happen in this codebase
